version: '3.1'

services:
        redmine:
                image: redmine:latest
                restart: always
                container_name: redmine
                networks:
                        - default
                        - redmine_network
                ports:
                        - 3000:3000
                volumes:
                    /var/lib/redmine_data
                environment:
                        REDMINE_DB_MYSQL: db
                        REDMINE_DB_PASSWORD: redmine
                        REDMINE_DB_DATABASE: redmine
                        REDMINE_DB_ENCODING: utf8
                        #REDMINE_NO_DB_MIGRATE: true
        mariadb:
                image: mairadb:latest
                restart: always
                container_name: miriadb
                networks:
                        - redmine_network
                ports:
                        - 3306:3306
                volumes:
                    /var/lib/myriadb_data
                environment:
                        MYSQL_ROOT_PASSWORD: redmine
                        MYSQL_DATABASE: redmine
                command:
                        - --character-set-server=utf8mb4
                        - --collation-server=utf8mb4_unicode_ci
networks:
        redmine_network: