version: '3.3'

services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - '9095:8080'
      - '50000:50000'
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ./volumes/jenkins_data:/var/jenkins_home

  nexus:
    container_name: nexus
    restart: always
    image: sonatype/nexus3
    ports:
      - '9195:8081'
    volumes:
      - ./volumes/nexus-data:/nexus-data

  scm-manager:
    container_name: scm-manager
    restart: always
    image: sdorra/scm-manager
    volumes:
      - ./volumes/scm-server:/var/lib/scm
    environment:
      - TZ=Asia/Seoul
    ports:
      - '9295:8080'

  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_redmine
      - POSTGRESQL_DATABASE=bitnami_redmine
    volumes:
      - './volumes/redmine/postgresql:/bitnami/postgresql'

  redmine:
    image: 'bitnami/redmine:4'
    ports:
      - '8080:3000'
    environment:
      - REDMINE_DB_POSTGRES=postgresql
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
    volumes:
      - './volumes/redmine/redmine:/bitnami'
    depends_on:
      - postgresql
